apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp01-deployment
  namespace: myapps
  labels:
    app: myapp01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01 
    spec:
      containers:
      - name: nodeserver
        image: fdockerhub/myapp01
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: myapp01-service
  namespace: myapps
spec:
  selector:
    app: myapp01 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110